# sources:
#   - name: Wiki
#     handler:
#       openapi:
#         source: https://api.apis.guru/v2/specs/wikimedia.org/1.0.0/swagger.yaml

sources:
  - name: Covid
    handler:
      graphql:
        endpoint: https://covid-19-two-rust.vercel.app/api/graphql
serve:
  hostname: 0.0.0.0 