version: "3.7"
services:
  mesh:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
    - ./work/.meshrc.yaml:/work/.meshrc.yaml
    image: hiroyukiosaki/graphql-mesh:latest
    ports:
    - "4000:4000"
    stdin_open: true
    tty: true
  mesh-all:
    build:
      context: ./
      dockerfile: Dockerfile-all
      args:
        tag: latest
    volumes:
      - ./work/.meshrc.yaml:/work/.meshrc.yaml
    image: hiroyukiosaki/graphql-mesh:latest-all
    ports:
    - "4000:4000"
    stdin_open: true
    tty: true
  mesh-alpine:
    build:
      context: ./
      dockerfile: Dockerfile-alpine
    volumes:
    - ./work/.meshrc.yaml:/work/.meshrc.yaml
    image: hiroyukiosaki/graphql-mesh:latest-alpine
    ports:
    - "4000:4000"
    stdin_open: true
    tty: true
  mesh-all-alpine:
    build:
      context: ./
      dockerfile: Dockerfile-all-alpine
    volumes:
    - ./work/.meshrc.yaml:/work/.meshrc.yaml
    image: hiroyukiosaki/graphql-mesh:latest-all-alpine
    ports:
    - "4000:4000"
    stdin_open: true
    tty: true
    # command:
    # - sh
    # - -c 
    # - sleep 3600