ARG tag=latest
FROM hiroyukiosaki/graphql-mesh:${tag}
RUN yarn add \
  @graphql-mesh/openapi \
  @graphql-mesh/json-schema \
  @graphql-mesh/postgraphile \
  @graphql-mesh/grpc \
  @graphql-mesh/graphql \
  @graphql-mesh/soap \
  @graphql-mesh/mongoose \
  @graphql-mesh/odata \
  @graphql-mesh/thrift \
  @graphql-mesh/tuql \
  @graphql-mesh/mysql \
  @graphql-mesh/neo4j \
  @graphql-mesh/transform-federation \
  @graphql-mesh/transform-rename \
  @graphql-mesh/transform-prefix \
  @graphql-mesh/transform-cache \
  @graphql-mesh/transform-snapshot \
  @graphql-mesh/transform-mock \
  @graphql-mesh/transform-resolvers-composition \
  @graphql-mesh/transform-federation \
  @graphql-mesh/transform-filter-schema \
  @graphql-mesh/transform-naming-convention \
  @graphql-mesh/merger-federation \
  @apollo/gateway \
  apollo-server