.PHONY: build
build:
	cd docker && docker-compose mesh
	cd docker && docker-compose mesh-all
	cd docker && docker-compose mesh-alpine
	cd docker && docker-compose mesh-all-alpine
	cd docker && docker-compose push